- type: remove
  path: /variables/name=cf_mysql_mysql_admin_password
- type: remove
  path: /variables/name=cf_mysql_mysql_cluster_health_password
- type: remove
  path: /variables/name=cf_mysql_mysql_galera_healthcheck_endpoint_password
- type: remove
  path: /variables/name=cf_mysql_mysql_galera_healthcheck_password
- type: remove
  path: /variables/name=cf_mysql_proxy_api_password
- type: remove
  path: /variables/name=cc_database_password
