# We use community-postgres so all references to mysql variables can be removed
- type: remove
  path: /variables/name=cf_mysql_mysql_admin_password
- type: remove
  path: /variables/name=cf_mysql_mysql_cluster_health_password
- type: remove
  path: /variables/name=cf_mysql_mysql_galera_healthcheck_endpoint_password
- type: remove
  path: /variables/name=cf_mysql_mysql_galera_healthcheck_password
- type: remove
  path: /variables/name=cf_mysql_proxy_api_password
- type: remove
  path: /variables/name=cc_database_password

# first try without routing-api (there is an add on for it in the kit)
# - type: remove
#   path: /variables/name=routing_api_tls_client
# - type: remove
#   path: /variables/name=routing_api_tls
- type: remove
  path: /variables/name=routing_api_database_password
- type: remove
  path: /variables/name=uaa_clients_routing_api_client_secret

# unused ca's
- type: remove
  path: /variables/name=credhub_ca
- type: remove
  path: /variables/name=metric_scraper_ca

# without addon-logging
- type: remove
  path: /variables/name=loggr_udp_forwarder_tls
- type: remove
  path: /variables/name=forwarder_agent_metrics_tls

# unused variables should probably create and upstream issue to get rid of them
- type: remove
  path: /variables/name=cf_bosh_password
- type: remove
  path: /variables/name=log_cache_to_loggregator_agent

# cf-kit has no credhub
- type: remove
  path: /variables/name=credhub_tls
- type: remove
  path: /variables/name=credhub_database_password
- type: remove
  path: /variables/name=credhub_encryption_password
- type: remove
  path: /variables/name=credhub_admin_client_secret

# fix uaa saml key path
- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/login/saml/keys/default_key?
  value:
    key: "((uaa_login_saml.private_key))"
    certificate: "((uaa_login_saml.certificate))"
    passphrase: ""
